### ISSUE TITLE
hidden properties are not storing in history model

### ISSUE THREAD

**Issue by sureshbabugaddamgithub** [arondn2/loopback-changes-history-mixin#2]
Dear Rondon,

Generally, A hidden property is not sent in the JSON data in the application’s HTTP response but to store it in the database collection.
Example model
{
  "name": "Customer",
  "hidden":["mobileNumber"]
  "properties": {
    "name": "string",
    "email": "string",
    "mobileNumber: "string"
    "status": "string",
    "description": "string"
  },
  "mixins": {
    "ChangeHistory": true
  }
} 
In the above example, I want to hide the mobileNumber in HTTP response but want to store it in the database.
Now my issue is in the database, mobileNumber is showing in Customer collection but not in Customer_history collection.

How I can store hidden property also in the history of the collection/model.

Thanks You.

**Comment by sureshbabugaddamgithub** [comment]
file Name: loopback-changes-history-mixin.js
Line Number 74
Using || condition instead of && is solved my issue  to store the hidden fields also in the history table

  - const dataRaw = (instance && instance.toJSON()) || {};
 + const dataRaw = (instance || instance.toJSON()) || {};

**Comment by arondn2** [comment]
Hi @sureshbabugaddamgithub I will take a look to solve this issue because I think the solution above could bring another problems. Please reopen this issue.

**Comment by ilijaz** [comment]
> Hi @sureshbabugaddamgithub I will take a look to solve this issue because I think the solution above could bring another problems. Please reopen this issue.

Hi, any news about this? Have the same problem.

**Comment by ilijaz** [comment]
I think this is right

` (instance && instance.toObject()) || {}; `

**Comment by arondn2** [comment]
Solved in version 0.2.5. I will close this issue,
